// Optimal SVGO configuration for musical notation SVG
// Generated by Incremental SVGO Test Framework
// Original size: 3,100,574 bytes
// Optimized size: 2,465,754 bytes  
// Size reduction: 20.5%
// Working plugins: 11/56

module.exports = {
  plugins: [
    "addAttributesToSVGElement",
    "cleanupEnableBackground",
    "cleanupListOfValues",
    "cleanupNumericValues",
    "collapseGroups",
    "convertPathData",
    "convertShapeToPath",
    "convertStyleToAttrs",
    "convertTransform",
    "mergePaths",
    "removeOffCanvasPaths"
],
  multipass: true
};
